/** @type {import('tailwindcss').Config} */

module.exports = {
  content: ['./src/**/*.{js,ts,jsx,tsx,mdx}', './app/**/*.{js,ts,jsx,tsx,mdx}'],
  theme: {
    extend: {
      backgroundColor: {
        base: 'var(--bg-layer-00)',
        card: 'var(--bg-layer-01)',
        'card-hover': 'var(--bg-layer-02)',
        'card-active': 'var(--bg-layer-03)',
        'card-selected': 'var(--bg-layer-04)',
        area: {
          DEFAULT: 'var(--bg-layer-00)',
          hover: 'var(--bg-layer-02)',
          selected: 'var(--bg-layer-03)',
        },
        dropdown: {
          DEFAULT: 'var(--bg-layer-03)',
          hover: 'var(--bg-layer-04)',
          selected: 'var(--bg-layer-05)',
        },
      },
      borderColor: {
        default: 'var(--border-00)',
      },
      textColor: {
        default: 'var(--text-00)',
        muted: 'var(--text-01)',
        'muted-hover': 'var(--text-02)',
        'muted-active': 'var(--text-03)',
        'muted-selected': 'var(--text-04)',
        'muted-disabled': 'var(--text-05)',
        'muted-disabled-hover': 'var(--text-06)',
        'muted-disabled-active': 'var(--text-07)',
        'muted-disabled-selected': 'var(--text-08)',
      },
      maxWidth: {
        3: '0.75rem',
        3.5: '0.875rem',
        4: '1rem',
        5: '1.25rem',
        6: '1.5rem',
        7: '1.75rem',
        8: '2rem',
        12: '3rem',
        20: '5rem',
        50: '12.5rem',
        60: '15rem',
        70: '17.5rem',
        80: '20rem',
        90: '22.5rem',
        100: '25rem',
        120: '30rem',
      },
      minWidth: {
        3: '0.75rem',
        3.5: '0.875rem',
        4: '1rem',
        5: '1.25rem',
        6: '1.5rem',
        7: '1.75rem',
        8: '2rem',
        12: '3rem',
        20: '5rem',
        50: '12.5rem',
        60: '15rem',
        70: '17.5rem',
        80: '20rem',
        90: '22.5rem',
        100: '25rem',
        120: '30rem',
      },
    },
  },
};
